import type { Artwork, Collection } from "@/types";

export const placeholderCollections: Collection[] = [
  {
    id: "c1",
    name: "Nature's Symphony",
    slug: "natures-symphony",
    description: "A celebration of the natural world — from sweeping landscapes to intimate botanical studies.",
    cover_image: "/images/collections/nature.svg",
    created_at: "2024-01-01",
  },
  {
    id: "c2",
    name: "Abstract Emotions",
    slug: "abstract-emotions",
    description: "Pure feeling translated into color and form. These pieces speak the language of the subconscious.",
    cover_image: "/images/collections/abstract.svg",
    created_at: "2024-01-01",
  },
  {
    id: "c3",
    name: "Himalayan Light",
    slug: "himalayan-light",
    description: "Inspired by a transformative journey through the Himalayas — capturing the sacred light of high altitude.",
    cover_image: "/images/collections/himalayan.svg",
    created_at: "2024-01-01",
  },
  {
    id: "c4",
    name: "Portraits of Silence",
    slug: "portraits-of-silence",
    description: "Quiet moments captured in paint. Figures lost in thought, solitude as strength.",
    cover_image: "/images/collections/portraits.svg",
    created_at: "2024-01-01",
  },
];

export const placeholderArtworks: Artwork[] = [
  {
    id: "a1",
    title: "Golden Hour Meadow",
    slug: "golden-hour-meadow",
    description: "A vast meadow bathed in the warm light of sunset, where wildflowers dance in an evening breeze.",
    story: "I painted this on location over three evenings, racing against the fading light each day. The golden hour lasts only minutes, but its memory stays forever.",
    price: 4500,
    currency: "USD",
    medium: "Oil on Canvas",
    height: 90,
    width: 120,
    depth: null,
    year_created: 2024,
    status: "available",
    featured: true,
    collection_id: "c1",
    created_at: "2024-06-01",
    images: [{ id: "i1", artwork_id: "a1", image_url: "/images/artworks/golden-hour-meadow.svg", display_order: 0 }],
    tags: [{ id: "t1", name: "landscape" }, { id: "t3", name: "nature" }],
    collection: placeholderCollections[0],
  },
  {
    id: "a2",
    title: "Depths Unseen",
    slug: "depths-unseen",
    description: "An abstract exploration of what lies beneath the surface — layers of consciousness revealed through color.",
    story: "This piece emerged during a period of deep introspection. Each layer represents a truth I was uncovering about myself.",
    price: 6200,
    currency: "USD",
    medium: "Acrylic on Canvas",
    height: 150,
    width: 120,
    depth: null,
    year_created: 2024,
    status: "available",
    featured: true,
    collection_id: "c2",
    created_at: "2024-05-01",
    images: [{ id: "i2", artwork_id: "a2", image_url: "/images/artworks/depths-unseen.svg", display_order: 0 }],
    tags: [{ id: "t2", name: "abstract" }, { id: "t9", name: "contemporary" }],
    collection: placeholderCollections[1],
  },
  {
    id: "a3",
    title: "Summit Prayer",
    slug: "summit-prayer",
    description: "The first light striking a Himalayan peak, sacred and untouched.",
    story: "Standing at 4,000 meters, watching dawn break over the peaks, I understood why ancient peoples worshipped mountains.",
    price: 8500,
    currency: "USD",
    medium: "Oil on Canvas",
    height: 100,
    width: 150,
    depth: null,
    year_created: 2023,
    status: "sold",
    featured: true,
    collection_id: "c3",
    created_at: "2024-04-01",
    images: [{ id: "i3", artwork_id: "a3", image_url: "/images/artworks/summit-prayer.svg", display_order: 0 }],
    tags: [{ id: "t4", name: "mountain" }, { id: "t1", name: "landscape" }],
    collection: placeholderCollections[2],
  },
  {
    id: "a4",
    title: "The Reader",
    slug: "the-reader",
    description: "A woman absorbed in a book by a rain-streaked window, lost in another world.",
    story: "My grandmother used to read every afternoon by the window. This is my tribute to those quiet, sacred hours.",
    price: 3800,
    currency: "USD",
    medium: "Oil on Canvas",
    height: 80,
    width: 60,
    depth: null,
    year_created: 2024,
    status: "available",
    featured: true,
    collection_id: "c4",
    created_at: "2024-03-01",
    images: [{ id: "i4", artwork_id: "a4", image_url: "/images/artworks/the-reader.svg", display_order: 0 }],
    tags: [{ id: "t5", name: "portrait" }, { id: "t12", name: "minimalist" }],
    collection: placeholderCollections[3],
  },
  {
    id: "a5",
    title: "Monsoon Rising",
    slug: "monsoon-rising",
    description: "Dark clouds gathering over a valley, the tension before the first raindrop falls.",
    story: "There is a moment of absolute stillness before a storm. Everything holds its breath. This is that moment.",
    price: 5200,
    currency: "USD",
    medium: "Oil on Canvas",
    height: 100,
    width: 130,
    depth: null,
    year_created: 2023,
    status: "available",
    featured: true,
    collection_id: "c1",
    created_at: "2024-02-01",
    images: [{ id: "i5", artwork_id: "a5", image_url: "/images/artworks/monsoon-rising.svg", display_order: 0 }],
    tags: [{ id: "t1", name: "landscape" }, { id: "t8", name: "sky" }],
    collection: placeholderCollections[0],
  },
  {
    id: "a6",
    title: "Cerulean Dreams",
    slug: "cerulean-dreams",
    description: "A meditation on blue — from the deepest ocean to the lightest sky.",
    story: "Blue is the color of infinity. This piece is my attempt to capture what it feels like to stare into endless space.",
    price: 4800,
    currency: "USD",
    medium: "Mixed Media on Canvas",
    height: 120,
    width: 120,
    depth: null,
    year_created: 2024,
    status: "available",
    featured: true,
    collection_id: "c2",
    created_at: "2024-01-01",
    images: [{ id: "i6", artwork_id: "a6", image_url: "/images/artworks/cerulean-dreams.svg", display_order: 0 }],
    tags: [{ id: "t2", name: "abstract" }, { id: "t7", name: "water" }, { id: "t8", name: "sky" }],
    collection: placeholderCollections[1],
  },
  {
    id: "a7",
    title: "Valley of Echoes",
    slug: "valley-of-echoes",
    description: "A misty Himalayan valley where sound seems to linger and multiply.",
    story: "In the valleys between peaks, even silence has a sound. I wanted to paint that acoustic quality of space.",
    price: 7200,
    currency: "USD",
    medium: "Oil on Canvas",
    height: 90,
    width: 140,
    depth: null,
    year_created: 2023,
    status: "reserved",
    featured: false,
    collection_id: "c3",
    created_at: "2023-11-01",
    images: [{ id: "i7", artwork_id: "a7", image_url: "/images/artworks/valley-of-echoes.svg", display_order: 0 }],
    tags: [{ id: "t4", name: "mountain" }, { id: "t3", name: "nature" }],
    collection: placeholderCollections[2],
  },
  {
    id: "a8",
    title: "Still Life with Time",
    slug: "still-life-with-time",
    description: "A contemplative arrangement of objects that speak of passing moments.",
    story: "Each object in this painting belonged to someone who taught me something important about life.",
    price: 3200,
    currency: "USD",
    medium: "Oil on Canvas",
    height: 60,
    width: 80,
    depth: null,
    year_created: 2024,
    status: "available",
    featured: false,
    collection_id: null,
    created_at: "2023-10-01",
    images: [{ id: "i8", artwork_id: "a8", image_url: "/images/artworks/still-life-with-time.svg", display_order: 0 }],
    tags: [{ id: "t12", name: "minimalist" }, { id: "t9", name: "contemporary" }],
  },
  {
    id: "a9",
    title: "Autumn Requiem",
    slug: "autumn-requiem",
    description: "The final blaze of color before winter, a forest saying goodbye.",
    story: "Every autumn I visit the same forest. Each year the farewell feels more poignant, more beautiful.",
    price: 5800,
    currency: "USD",
    medium: "Oil on Canvas",
    height: 100,
    width: 140,
    depth: null,
    year_created: 2022,
    status: "sold",
    featured: false,
    collection_id: "c1",
    created_at: "2023-09-01",
    images: [{ id: "i9", artwork_id: "a9", image_url: "/images/artworks/autumn-requiem.svg", display_order: 0 }],
    tags: [{ id: "t1", name: "landscape" }, { id: "t3", name: "nature" }],
    collection: placeholderCollections[0],
  },
  {
    id: "a10",
    title: "Inner Landscape",
    slug: "inner-landscape",
    description: "Where the mind meets the horizon. An abstract landscape of thought.",
    story: "What does thinking look like? If consciousness had a landscape, this is what I imagine it might be.",
    price: 4200,
    currency: "USD",
    medium: "Acrylic on Canvas",
    height: 100,
    width: 100,
    depth: null,
    year_created: 2024,
    status: "available",
    featured: false,
    collection_id: "c2",
    created_at: "2023-08-01",
    images: [{ id: "i10", artwork_id: "a10", image_url: "/images/artworks/inner-landscape.svg", display_order: 0 }],
    tags: [{ id: "t2", name: "abstract" }, { id: "t9", name: "contemporary" }],
    collection: placeholderCollections[1],
  },
];

export const placeholderTags = [
  { id: "t1", name: "landscape" },
  { id: "t2", name: "abstract" },
  { id: "t3", name: "nature" },
  { id: "t4", name: "mountain" },
  { id: "t5", name: "portrait" },
  { id: "t6", name: "floral" },
  { id: "t7", name: "water" },
  { id: "t8", name: "sky" },
  { id: "t9", name: "contemporary" },
  { id: "t10", name: "large-scale" },
  { id: "t11", name: "textured" },
  { id: "t12", name: "minimalist" },
];
